// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.1
// source: proto/funcionario.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "funcionario";

export interface GetFuncionarioRequest {
  id: string;
}

export interface FuncionarioResponse {
  id: string;
  nome: string;
  cargoId: string;
  departamentoId: string;
  salario: number;
}

export const FUNCIONARIO_PACKAGE_NAME = "funcionario";

export interface FuncionarioServiceClient {
  getFuncionario(request: GetFuncionarioRequest): Observable<FuncionarioResponse>;
}

export interface FuncionarioServiceController {
  getFuncionario(
    request: GetFuncionarioRequest,
  ): Promise<FuncionarioResponse> | Observable<FuncionarioResponse> | FuncionarioResponse;
}

export function FuncionarioServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getFuncionario"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FuncionarioService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FuncionarioService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const FUNCIONARIO_SERVICE_NAME = "FuncionarioService";
