// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v7.36.1
// source: proto/departamento.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "departamento";

export interface GetDepartamentoRequest {
  id: string;
}

export interface DepartamentoResponse {
  id: string;
  nome: string;
}

export interface GetCargoRequest {
  cargoId: string;
  departamentoId: string;
}

export interface CargoResponse {
  id: string;
  nome: string;
  departamentoId: string;
}

export const DEPARTAMENTO_PACKAGE_NAME = "departamento";

export interface DepartamentoServiceClient {
  getDepartamento(request: GetDepartamentoRequest): Observable<DepartamentoResponse>;

  getCargo(request: GetCargoRequest): Observable<CargoResponse>;
}

export interface DepartamentoServiceController {
  getDepartamento(
    request: GetDepartamentoRequest,
  ): Promise<DepartamentoResponse> | Observable<DepartamentoResponse> | DepartamentoResponse;

  getCargo(request: GetCargoRequest): Promise<CargoResponse> | Observable<CargoResponse> | CargoResponse;
}

export function DepartamentoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getDepartamento", "getCargo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DepartamentoService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DepartamentoService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const DEPARTAMENTO_SERVICE_NAME = "DepartamentoService";
