// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v7.36.1
// source: proto/departamento.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "departamento";

export interface GetDepartamentoRequest {
  id: string;
}

export interface ListByIdsRequest {
  ids: string[];
}

export interface DepartamentoResponse {
  id: string;
  nome: string;
}

export interface DepartamentosResponse {
  departamentos: DepartamentoResponse[];
}

export interface GetCargoRequest {
  cargoId: string;
  departamentoId: string;
}

export interface CargoResponse {
  id: string;
  nome: string;
  departamentoId: string;
  salarioBase: number;
  salarioTeto: number;
}

export interface CargosResponse {
  cargos: CargoResponse[];
}

export const DEPARTAMENTO_PACKAGE_NAME = "departamento";

export interface DepartamentoServiceClient {
  getDepartamento(request: GetDepartamentoRequest): Observable<DepartamentoResponse>;

  getDepartamentos(request: ListByIdsRequest): Observable<DepartamentosResponse>;

  getCargo(request: GetCargoRequest): Observable<CargoResponse>;

  getCargos(request: ListByIdsRequest): Observable<CargosResponse>;
}

export interface DepartamentoServiceController {
  getDepartamento(
    request: GetDepartamentoRequest,
  ): Promise<DepartamentoResponse> | Observable<DepartamentoResponse> | DepartamentoResponse;

  getDepartamentos(
    request: ListByIdsRequest,
  ): Promise<DepartamentosResponse> | Observable<DepartamentosResponse> | DepartamentosResponse;

  getCargo(request: GetCargoRequest): Promise<CargoResponse> | Observable<CargoResponse> | CargoResponse;

  getCargos(request: ListByIdsRequest): Promise<CargosResponse> | Observable<CargosResponse> | CargosResponse;
}

export function DepartamentoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getDepartamento", "getDepartamentos", "getCargo", "getCargos"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DepartamentoService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DepartamentoService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const DEPARTAMENTO_SERVICE_NAME = "DepartamentoService";
