// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.1
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface LoginRequest {
  email: string;
  senha: string;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface LogoutRequest {
  refreshToken: string;
}

export interface LogoutResponse {
  success: boolean;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  usuario: UsuarioResponse | undefined;
}

export interface CriarUsuarioRequest {
  email: string;
  senha: string;
  roles: string[];
  funcionarioId: string;
}

export interface GetUsuarioRequest {
  id: string;
}

export interface UsuarioResponse {
  id: string;
  email: string;
  roles: string[];
  funcionarioId: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  login(request: LoginRequest): Observable<AuthResponse>;

  refresh(request: RefreshRequest): Observable<AuthResponse>;

  logout(request: LogoutRequest): Observable<LogoutResponse>;

  criarUsuario(request: CriarUsuarioRequest): Observable<UsuarioResponse>;

  getUsuario(request: GetUsuarioRequest): Observable<UsuarioResponse>;
}

export interface AuthServiceController {
  login(request: LoginRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  refresh(request: RefreshRequest): Promise<AuthResponse> | Observable<AuthResponse> | AuthResponse;

  logout(request: LogoutRequest): Promise<LogoutResponse> | Observable<LogoutResponse> | LogoutResponse;

  criarUsuario(request: CriarUsuarioRequest): Promise<UsuarioResponse> | Observable<UsuarioResponse> | UsuarioResponse;

  getUsuario(request: GetUsuarioRequest): Promise<UsuarioResponse> | Observable<UsuarioResponse> | UsuarioResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "refresh", "logout", "criarUsuario", "getUsuario"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
